#!/usr/bin/env bash
# Configure Howdy for Surface IR (Surface-IR-Howdy) — distro-neutral.
# Empty-password face login is installed by tools/install-face-login-safe.sh.
# Typed passwords stay on stock PAM (no pam_howdy in the greeter).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# When installed to /usr/local/sbin, templates live next to us or under PREFIX.
for cand in "$ROOT" /opt/surface-cameras /usr/local/share/surface-cameras; do
  [[ -d "$cand/etc-pam" ]] && ROOT="$cand" && break
done

resolve_ir() {
  for ent in /sys/class/video4linux/video*; do
    [[ -e "$ent/name" ]] || continue
    name=$(cat "$ent/name" 2>/dev/null || true)
    if [[ "$name" == "Surface-IR-Howdy" ]]; then
      echo "/dev/$(basename "$ent")"
      return 0
    fi
  done
  return 1
}

IR_DEV=$(resolve_ir) || IR_DEV=""
if [[ -z "$IR_DEV" ]]; then
  echo "Surface-IR-Howdy missing — writing config with placeholder (scan no-ops until webcamd)"
  IR_DEV="/dev/video66"
else
  echo "Howdy IR loopback: $IR_DEV"
fi

python3 - "$IR_DEV" <<'PY'
import sys
from pathlib import Path

ir = sys.argv[1]
p = Path("/etc/howdy/config.ini")
text = f"""# Howdy — Surface Book 3 IR (Surface-IR-Howdy)
# Generated by configure-howdy-ir.sh — empty-password face login via face-pam-auth.

[core]
detection_notice = false
timeout_notice = false
no_confirmation = true
suppress_unknown = true
abort_if_ssh = true
abort_if_lid_closed = true
disabled = false
use_cnn = false
workaround = off

[video]
certainty = 4.5
timeout = 5
device_path = {ir}
warn_no_device = false
max_height = 640
frame_width = 480
frame_height = 640
dark_threshold = 90
recording_plugin = opencv
device_format = v4l2
force_mjpeg = false
exposure = -1
device_fps = 30
rotate = 0

[snapshots]
save_failed = false
save_successful = false

[rubberstamps]
enabled = false
stamp_rules =

[debug]
end_report = false
verbose_stamps = false
gtk_stdout = false
"""
p.parent.mkdir(parents=True, exist_ok=True)
p.write_text(text)
print(f"Wrote {p}: device_path={ir}")
PY

rm -f /etc/howdy/force-disabled

install_helpers() {
  local d
  for d in /usr/local/sbin /usr/local/bin; do
    install -d "$d"
  done
  for f in surface-howdy-gate.sh surface-ir-wait-auth.sh surface-ir-pam-session.sh; do
    if [[ -f "$ROOT/sbin/$f" ]]; then
      install -m 755 "$ROOT/sbin/$f" "/usr/local/sbin/$f"
      restorecon -F "/usr/local/sbin/$f" 2>/dev/null || chcon -t bin_t "/usr/local/sbin/$f" 2>/dev/null || true
    fi
  done
}

install_password_pam() {
  # Prefer package defaults; fall back to templates (no pam_howdy in greeter/lock).
  if [[ -f /usr/lib/pam.d/plasmalogin ]]; then
    install -m 644 /usr/lib/pam.d/plasmalogin /etc/pam.d/plasmalogin
  elif [[ -f "$ROOT/etc-pam/plasmalogin" ]]; then
    install -m 644 "$ROOT/etc-pam/plasmalogin" /etc/pam.d/plasmalogin
  fi
  for pam in plasmalogin kde kscreensaver; do
    f="/etc/pam.d/$pam"
    [[ -f "$f" ]] || continue
    python3 - "$f" <<'PY'
import sys
from pathlib import Path
p = Path(sys.argv[1])
drop = ("pam_howdy.so", "surface-ir-wait-auth", "surface-howdy-only-if-empty",
        "surface-face-auth-prepare", "greeter-hint", "pam_echo.so")
lines = []
for l in p.read_text().splitlines():
    if l.strip().startswith("auth") and any(x in l for x in drop):
        continue
    lines.append(l)
if not any("surface-ir-pam-session" in l for l in lines):
    lines.append("session     optional      pam_exec.so quiet /usr/local/sbin/surface-ir-pam-session.sh")
p.write_text("\n".join(lines) + "\n")
print("password-only PAM:", p)
PY
  done
  if [[ -f /etc/pam.d/kde ]] && ! grep -q 'password-auth\|system-auth' /etc/pam.d/kde; then
    [[ -f "$ROOT/etc-pam/kde" ]] && install -m 644 "$ROOT/etc-pam/kde" /etc/pam.d/kde
  fi
}

install_face_login() {
  local script=""
  for cand in \
    "$ROOT/tools/install-face-login-safe.sh" \
    /opt/surface-cameras/tools/install-face-login-safe.sh
  do
    [[ -f "$cand" ]] && script="$cand" && break
  done
  if [[ -n "$script" ]]; then
    bash "$script" || true
  else
    echo "install-face-login-safe.sh missing — skip PAM face hook" >&2
  fi
  if command -v systemctl >/dev/null; then
    systemctl daemon-reload
    systemctl disable --now surface-face-login.path surface-face-greeter-button.service \
      surface-howdy-enable.service 2>/dev/null || true
    systemctl disable --now surface-howdy-prefetch.service surface-howdy-warm.service \
      surface-howdy-clear-autologin.service 2>/dev/null || true
    for u in surface-ir-howdy.service surface-howdy-cameras.path surface-howdy-cameras.service \
             surface-face-login.path surface-face-greeter-button.service; do
      systemctl disable --now "$u" 2>/dev/null || true
      ln -sfn /dev/null "/etc/systemd/system/$u" 2>/dev/null || true
    done
  fi
}

install_helpers
install_password_pam
install_face_login

echo "Howdy IR configured. Typed password = stock PAM. Empty password = face scan."
echo "Enroll: surface-howdy-add-profile   Test: sudo howdy --user \"\$USER\" test"
