#!/usr/bin/env bash
# Configure Howdy for Surface Book 3 IR via Surface-IR-Howdy loopback (English).
# Writes a complete valid INI (Howdy 3 requires [core]/[video]/…).
# Resolves the loopback by card name — /dev/video* numbers may swap across boots.
set -euo pipefail

resolve_ir() {
  for ent in /sys/class/video4linux/video*; do
    [[ -e "$ent/name" ]] || continue
    name=$(cat "$ent/name" 2>/dev/null || true)
    if [[ "$name" == "Surface-IR-Howdy" ]]; then
      echo "/dev/$(basename "$ent")"
      return 0
    fi
  done
  return 1
}

IR_DEV=$(resolve_ir) || { echo "Surface-IR-Howdy loopback missing (load v4l2loopback)"; exit 1; }
echo "Howdy IR loopback: $IR_DEV"

python3 - "$IR_DEV" <<'PY'
import sys
from pathlib import Path

ir = sys.argv[1]
p = Path("/etc/howdy/config.ini")
# Portrait after webcamd rot90 — native 480×640, no FHD upscale.
text = f"""# Howdy — Surface Book 3 IR (Surface-IR-Howdy)
# Generated by configure-howdy-ir.sh — do not flatten keys outside sections.

[core]
detection_notice = false
timeout_notice = false
no_confirmation = true
suppress_unknown = true
abort_if_ssh = true
abort_if_lid_closed = true
disabled = false
use_cnn = false
# input: send Enter after timeout so KDE lock does not sit forever
# off: safer on Wayland — input/native caused lock hangs / black screens
workaround = off

[video]
certainty = 4.5
timeout = 5
device_path = {ir}
warn_no_device = false
# IR loopback is already 480×640 portrait (webcamd rot90)
max_height = 640
frame_width = 480
frame_height = 640
# IR LED frames score "dark" high on Howdy's histogram metric — 50 rejects all
dark_threshold = 90
recording_plugin = opencv
device_format = v4l2
force_mjpeg = false
exposure = -1
device_fps = 30
rotate = 0

[snapshots]
save_failed = false
save_successful = false

[rubberstamps]
enabled = false
stamp_rules =

[debug]
end_report = false
verbose_stamps = false
gtk_stdout = false
"""
p.parent.mkdir(parents=True, exist_ok=True)
p.write_text(text)
print(f"Wrote {p}: device_path={ir} disabled=false opencv 480x640")
PY

# Allow Howdy to run (empty force-disabled blocks all auth)
rm -f /etc/howdy/force-disabled

# PAM: lock (kde) + greeter (plasmalogin). sudo stays password-only by default.
ensure_howdy_pam() {
  local pam=$1
  [[ -f "$pam" ]] || return 0
  if grep -q 'pam_howdy.so' "$pam"; then
    echo "PAM ok: $pam"
    return 0
  fi
  python3 - "$pam" <<'PY'
from pathlib import Path
import sys
p = Path(sys.argv[1])
lines = p.read_text().splitlines(True)
# Insert after wait-auth if present, else after PAM header
insert_at = 0
for i, line in enumerate(lines):
    if line.startswith("#") or line.strip() == "":
        insert_at = i + 1
        continue
    if "surface-ir-wait-auth" in line:
        insert_at = i + 1
        break
    if line.startswith("auth"):
        insert_at = i
        break
howdy = "auth        sufficient  pam_howdy.so\n"
lines.insert(insert_at, howdy)
p.write_text("".join(lines))
print(f"PAM: inserted pam_howdy.so into {p}")
PY
}

ensure_howdy_pam /etc/pam.d/kde
# Greeter (cold boot + switch user) — same stack as lock; wait-auth nudges IR first.
ensure_howdy_pam /etc/pam.d/plasmalogin

# Enable Howdy after webcamd (do not leave boot gate forcing disabled=true)
if [[ -f /etc/systemd/system/surface-howdy-enable.service ]]; then
  systemctl disable --now surface-howdy-gate.service 2>/dev/null || true
  mkdir -p /etc/systemd/system/surface-howdy-enable.service.d
  cat >/etc/systemd/system/surface-howdy-enable.service.d/after-webcam.conf <<'EOF'
[Unit]
Description=Enable Howdy PAM after Surface webcamd is ready
After=surface-webcam.service surface-ipu4-late.service
Wants=surface-webcam.service

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable surface-howdy-enable.service 2>/dev/null || true
  /usr/local/sbin/surface-howdy-gate.sh --enable 2>/dev/null || true
fi

echo "Howdy configured. Enroll: Howdy — Add Face Profile (menu) or surface-howdy-add-profile"
